"""add title and updated_at columns

Revision ID: baea7cc80975
Revises: bcd973c478f2
Create Date: 2026-01-01 17:51:34.981394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baea7cc80975'
down_revision: Union[str, Sequence[str], None] = 'bcd973c478f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('title', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'title')
    # ### end Alembic commands ###
