from pydantic import BaseModel
from typing import Optional, List, Dict, Any
from datetime import datetime

class EngagementMedia(BaseModel):
    type: str # "image", "video", "thumbnail", "embed"
    url: str

class EngagementAuthor(BaseModel):
    name: str
    handle: Optional[str] = None
    avatar: Optional[str] = None
    profile_url: Optional[str] = None

class EngagementMetrics(BaseModel):
    likes: int = 0
    shares: int = 0 # retweets
    views: Optional[int] = 0
    comments: int = 0

class EngagementPostDomain(BaseModel):
    id: Optional[str] = None # Generated by DB
    source: str # "twitter" | "youtube"
    source_id: str
    title: Optional[str] = None
    text: Optional[str] = None
    url: str
    media: List[EngagementMedia] = []
    author: EngagementAuthor
    metrics: EngagementMetrics
    published_at: datetime
    fetched_at: datetime